---

- name: Create internal interface
  template: src="templates/internal_iface.cfg.j2" dest="/etc/network/interfaces.d/{{internal_iface}}.cfg" owner=root group=root mode=0644
  tags:
    - network

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ip_eth1 }} {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname_short }}"
    state: present
  with_items: "{{ groups.all }}"

- name: Restart all network interfaces except loopback device
  shell: "ifdown --exclude=lo -a; sleep 1; ifup --exclude=lo -a"
  tags:
    - network
